name: Build and Push Docker Image to ACR

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Docker build
        working-directory: ./TestWebProject.Web/TestWebProject.Web.Api/
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/testwebapp:latest .

      - name: Docker push
        run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/testwebapp:latest
